id: I77BB9BBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:56:29+00:00'
last_modified: '2022-06-08T12:42:36.706717+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294434
  title: རིག་འདུས་བསྙེན་ཡིག་ཀུན་འདུས་དངོས་གྲུབ་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D457:
      image_group_id: I4CZ294541
      title: ''
      total_pages: 902
      order: 1
      base_file: D457.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
